const config = require('../../config');
const secret = config.SECRETS;
const {db, models: {
    Country
}} = require('../../src/db/models');


(async () => {
    try {
        await Country.bulkCreate([
            { name: "Afghanistan", dial_code: "+93", id: "AF" },
            { name: "Albania", dial_code: "+355", id: "AL" },
            { name: "Algeria", dial_code: "+213", id: "DZ" },
            { name: "AmericanSamoa", dial_code: "+1684", id: "AS" },
            { name: "Andorra", dial_code: "+376", id: "AD" },
            { name: "Angola", dial_code: "+244", id: "AO" },
            { name: "Anguilla", dial_code: "+1264", id: "AI" },
            { name: "Antigua and Barbuda", dial_code: "+1268", id: "AG" },
            { name: "Argentina", dial_code: "+54", id: "AR" },
            { name: "Armenia", dial_code: "+374", id: "AM" },
            { name: "Aruba", dial_code: "+297", id: "AW" },
            { name: "Australia", dial_code: "+61", id: "AU" },
            { name: "Austria", dial_code: "+43", id: "AT" },
            { name: "Azerbaijan", dial_code: "+994", id: "AZ" },
            { name: "Bahamas", dial_code: "+1242", id: "BS" },
            { name: "Bahrain", dial_code: "+973", id: "BH" },
            { name: "Bangladesh", dial_code: "+880", id: "BD" },
            { name: "Barbados", dial_code: "+1246", id: "BB" },
            { name: "Belarus", dial_code: "+375", id: "BY" },
            { name: "Belgium", dial_code: "+32", id: "BE" },
            { name: "Belize", dial_code: "+501", id: "BZ" },
            { name: "Benin", dial_code: "+229", id: "BJ" },
            { name: "Bermuda", dial_code: "+1441", id: "BM" },
            { name: "Bhutan", dial_code: "+975", id: "BT" },
            { name: "Bosnia and Herzegovina", dial_code: "+387", id: "BA" },
            { name: "Botswana", dial_code: "+267", id: "BW" },
            { name: "Brazil", dial_code: "+55", id: "BR" },
            { name: "British Indian Ocean Territory", dial_code: "+246", id: "IO" },
            { name: "Bulgaria", dial_code: "+359", id: "BG" },
            { name: "Burkina Faso", dial_code: "+226", id: "BF" },
            { name: "Burundi", dial_code: "+257", id: "BI" },
            { name: "Cambodia", dial_code: "+855", id: "KH" },
            { name: "Cameroon", dial_code: "+237", id: "CM" },
            { name: "Canada", dial_code: "+1", id: "CA" },
            { name: "Cape Verde", dial_code: "+238", id: "CV" },
            { name: "Cayman Islands", dial_code: "+345", id: "KY" },
            { name: "Central African Republic", dial_code: "+236", id: "CF" },
            { name: "Chad", dial_code: "+235", id: "TD" },
            { name: "Chile", dial_code: "+56", id: "CL" },
            { name: "China", dial_code: "+86", id: "CN" },
            { name: "Christmas Island", dial_code: "+61", id: "CX" },
            { name: "Colombia", dial_code: "+57", id: "CO" },
            { name: "Comoros", dial_code: "+269", id: "KM" },
            { name: "Congo", dial_code: "+242", id: "CG" },
            { name: "Cook Islands", dial_code: "+682", id: "CK" },
            { name: "Costa Rica", dial_code: "+506", id: "CR" },
            { name: "Croatia", dial_code: "+385", id: "HR" },
            { name: "Cuba", dial_code: "+53", id: "CU" },
            { name: "Cyprus", dial_code: "+537", id: "CY" },
            { name: "Czech Republic", dial_code: "+420", id: "CZ" },
            { name: "Denmark", dial_code: "+45", id: "DK" },
            { name: "Djibouti", dial_code: "+253", id: "DJ" },
            { name: "Dominica", dial_code: "+1767", id: "DM" },
            { name: "Dominican Republic", dial_code: "+1849", id: "DO" },
            { name: "Ecuador", dial_code: "+593", id: "EC" },
            { name: "Egypt", dial_code: "+20", id: "EG" },
            { name: "El Salvador", dial_code: "+503", id: "SV" },
            { name: "Equatorial Guinea", dial_code: "+240", id: "GQ" },
            { name: "Eritrea", dial_code: "+291", id: "ER" },
            { name: "Estonia", dial_code: "+372", id: "EE" },
            { name: "Ethiopia", dial_code: "+251", id: "ET" },
            { name: "Faroe Islands", dial_code: "+298", id: "FO" },
            { name: "Fiji", dial_code: "+679", id: "FJ" },
            { name: "Finland", dial_code: "+358", id: "FI" },
            { name: "France", dial_code: "+33", id: "FR" },
            { name: "French Guiana", dial_code: "+594", id: "GF" },
            { name: "French Polynesia", dial_code: "+689", id: "PF" },
            { name: "Gabon", dial_code: "+241", id: "GA" },
            { name: "Gambia", dial_code: "+220", id: "GM" },
            { name: "Georgia", dial_code: "+995", id: "GE" },
            { name: "Germany", dial_code: "+49", id: "DE" },
            { name: "Ghana", dial_code: "+233", id: "GH" },
            { name: "Gibraltar", dial_code: "+350", id: "GI" },
            { name: "Greece", dial_code: "+30", id: "GR" },
            { name: "Greenland", dial_code: "+299", id: "GL" },
            { name: "Grenada", dial_code: "+1473", id: "GD" },
            { name: "Guadeloupe", dial_code: "+590", id: "GP" },
            { name: "Guam", dial_code: "+1671", id: "GU" },
            { name: "Guatemala", dial_code: "+502", id: "GT" },
            { name: "Guinea", dial_code: "+224", id: "GN" },
            { name: "Guinea-Bissau", dial_code: "+245", id: "GW" },
            { name: "Guyana", dial_code: "+595", id: "GY" },
            { name: "Haiti", dial_code: "+509", id: "HT" },
            { name: "Honduras", dial_code: "+504", id: "HN" },
            { name: "Hungary", dial_code: "+36", id: "HU" },
            { name: "Iceland", dial_code: "+354", id: "IS" },
            { name: "India", dial_code: "+91", id: "IN" },
            { name: "Indonesia", dial_code: "+62", id: "ID" },
            { name: "Iraq", dial_code: "+964", id: "IQ" },
            { name: "Ireland", dial_code: "+353", id: "IE" },
            { name: "Israel", dial_code: "+972", id: "IL" },
            { name: "Italy", dial_code: "+39", id: "IT" },
            { name: "Jamaica", dial_code: "+1876", id: "JM" },
            { name: "Japan", dial_code: "+81", id: "JP" },
            { name: "Jordan", dial_code: "+962", id: "JO" },
            { name: "Kazakhstan", dial_code: "+77", id: "KZ" },
            { name: "Kenya", dial_code: "+254", id: "KE" },
            { name: "Kiribati", dial_code: "+686", id: "KI" },
            { name: "Kuwait", dial_code: "+965", id: "KW" },
            { name: "Kyrgyzstan", dial_code: "+996", id: "KG" },
            { name: "Latvia", dial_code: "+371", id: "LV" },
            { name: "Lebanon", dial_code: "+961", id: "LB" },
            { name: "Lesotho", dial_code: "+266", id: "LS" },
            { name: "Liberia", dial_code: "+231", id: "LR" },
            { name: "Liechtenstein", dial_code: "+423", id: "LI" },
            { name: "Lithuania", dial_code: "+370", id: "LT" },
            { name: "Luxembourg", dial_code: "+352", id: "LU" },
            { name: "Madagascar", dial_code: "+261", id: "MG" },
            { name: "Malawi", dial_code: "+265", id: "MW" },
            { name: "Malaysia", dial_code: "+60", id: "MY" },
            { name: "Maldives", dial_code: "+960", id: "MV" },
            { name: "Mali", dial_code: "+223", id: "ML" },
            { name: "Malta", dial_code: "+356", id: "MT" },
            { name: "Marshall Islands", dial_code: "+692", id: "MH" },
            { name: "Martinique", dial_code: "+596", id: "MQ" },
            { name: "Mauritania", dial_code: "+222", id: "MR" },
            { name: "Mauritius", dial_code: "+230", id: "MU" },
            { name: "Mayotte", dial_code: "+262", id: "YT" },
            { name: "Mexico", dial_code: "+52", id: "MX" },
            { name: "Monaco", dial_code: "+377", id: "MC" },
            { name: "Mongolia", dial_code: "+976", id: "MN" },
            { name: "Montenegro", dial_code: "+382", id: "ME" },
            { name: "Montserrat", dial_code: "+1664", id: "MS" },
            { name: "Morocco", dial_code: "+212", id: "MA" },
            { name: "Myanmar", dial_code: "+95", id: "MM" },
            { name: "Namibia", dial_code: "+264", id: "NA" },
            { name: "Nauru", dial_code: "+674", id: "NR" },
            { name: "Nepal", dial_code: "+977", id: "NP" },
            { name: "Netherlands", dial_code: "+31", id: "NL" },
            { name: "Netherlands Antilles", dial_code: "+599", id: "AN" },
            { name: "New Caledonia", dial_code: "+687", id: "NC" },
            { name: "New Zealand", dial_code: "+64", id: "NZ" },
            { name: "Nicaragua", dial_code: "+505", id: "NI" },
            { name: "Niger", dial_code: "+227", id: "NE" },
            { name: "Nigeria", dial_code: "+234", id: "NG" },
            { name: "Niue", dial_code: "+683", id: "NU" },
            { name: "Norfolk Island", dial_code: "+672", id: "NF" },
            { name: "Northern Mariana Islands", dial_code: "+1670", id: "MP" },
            { name: "Norway", dial_code: "+47", id: "NO" },
            { name: "Oman", dial_code: "+968", id: "OM" },
            { name: "Pakistan", dial_code: "+92", id: "PK" },
            { name: "Palau", dial_code: "+680", id: "PW" },
            { name: "Panama", dial_code: "+507", id: "PA" },
            { name: "Papua New Guinea", dial_code: "+675", id: "PG" },
            { name: "Paraguay", dial_code: "+595", id: "PY" },
            { name: "Peru", dial_code: "+51", id: "PE" },
            { name: "Philippines", dial_code: "+63", id: "PH" },
            { name: "Poland", dial_code: "+48", id: "PL" },
            { name: "Portugal", dial_code: "+351", id: "PT" },
            { name: "Puerto Rico", dial_code: "+1939", id: "PR" },
            { name: "Qatar", dial_code: "+974", id: "QA" },
            { name: "Romania", dial_code: "+40", id: "RO" },
            { name: "Rwanda", dial_code: "+250", id: "RW" },
            { name: "Samoa", dial_code: "+685", id: "WS" },
            { name: "San Marino", dial_code: "+378", id: "SM" },
            { name: "Saudi Arabia", dial_code: "+966", id: "SA" },
            { name: "Senegal", dial_code: "+221", id: "SN" },
            { name: "Serbia", dial_code: "+381", id: "RS" },
            { name: "Seychelles", dial_code: "+248", id: "SC" },
            { name: "Sierra Leone", dial_code: "+232", id: "SL" },
            { name: "Singapore", dial_code: "+65", id: "SG" },
            { name: "Slovakia", dial_code: "+421", id: "SK" },
            { name: "Slovenia", dial_code: "+386", id: "SI" },
            { name: "Solomon Islands", dial_code: "+677", id: "SB" },
            { name: "South Africa", dial_code: "+27", id: "ZA" },
            { name: "South Georgia and the South Sandwich Islands", dial_code: "+500", id: "GS" },
            { name: "Spain", dial_code: "+34", id: "ES" },
            { name: "Sri Lanka", dial_code: "+94", id: "LK" },
            { name: "Sudan", dial_code: "+249", id: "SD" },
            { name: "Suriname", dial_code: "+597", id: "SR" },
            { name: "Swaziland", dial_code: "+268", id: "SZ" },
            { name: "Sweden", dial_code: "+46", id: "SE" },
            { name: "Switzerland", dial_code: "+41", id: "CH" },
            { name: "Tajikistan", dial_code: "+992", id: "TJ" },
            { name: "Thailand", dial_code: "+66", id: "TH" },
            { name: "Togo", dial_code: "+228", id: "TG" },
            { name: "Tokelau", dial_code: "+690", id: "TK" },
            { name: "Tonga", dial_code: "+676", id: "TO" },
            { name: "Trinidad and Tobago", dial_code: "+1868", id: "TT" },
            { name: "Tunisia", dial_code: "+216", id: "TN" },
            { name: "Turkey", dial_code: "+90", id: "TR" },
            { name: "Turkmenistan", dial_code: "+993", id: "TM" },
            { name: "Turks and Caicos Islands", dial_code: "+1649", id: "TC" },
            { name: "Tuvalu", dial_code: "+688", id: "TV" },
            { name: "Uganda", dial_code: "+256", id: "UG" },
            { name: "Ukraine", dial_code: "+380", id: "UA" },
            { name: "United Arab Emirates", dial_code: "+971", id: "AE" },
            { name: "United Kingdom", dial_code: "+44", id: "GB" },
            { name: "United States", dial_code: "+1", id: "US" },
            { name: "Uruguay", dial_code: "+598", id: "UY" },
            { name: "Uzbekistan", dial_code: "+998", id: "UZ" },
            { name: "Vanuatu", dial_code: "+678", id: "VU" },
            { name: "Wallis and Futuna", dial_code: "+681", id: "WF" },
            { name: "Yemen", dial_code: "+967", id: "YE" },
            { name: "Zambia", dial_code: "+260", id: "ZM" },
            { name: "Zimbabwe", dial_code: "+263", id: "ZW" },
            { name: "land Islands", dial_code: "+358", id: "AX" },
            { name: "Bolivia, Plurinational State of", dial_code: "+591", id: "BO" },
            { name: "Brunei Darussalam", dial_code: "+673", id: "BN" },
            { name: "Cocos (Keeling) Islands", dial_code: "+61", id: "CC" },
            { name: "The Democratic Republic of Congo", dial_code: "+243", id: "CD" },
            { name: "Cote d'Ivoire (Ivory Coast)", dial_code: "+225", id: "CI" },
            { name: "Falkland Islands (Malvinas)", dial_code: "+500", id: "FK" },
            { name: "Guernsey", dial_code: "+44", id: "GG" },
            { name: "Holy See (Vatican City State)", dial_code: "+379", id: "VA" },
            { name: "Hong Kong", dial_code: "+852", id: "HK" },
            { name: "Islamic Republic of Iran", dial_code: "+98", id: "IR" },
            { name: "Isle of Man", dial_code: "+44", id: "IM" },
            { name: "Jersey", dial_code: "+44", id: "JE" },
            { name: "Democratic People's Republic of Korea", dial_code: "+850", id: "KP" },
            { name: "Republic of Korea", dial_code: "+82", id: "KR" },
            { name: "Lao People's Democratic Republic", dial_code: "+856", id: "LA" },
            { name: "Libyan Arab Jamahiriya", dial_code: "+218", id: "LY" },
            { name: "Macao", dial_code: "+853", id: "MO" },
            { name: "Macedonia", dial_code: "+389", id: "MK" },
            { name: "Micronesia, Federated States of", dial_code: "+691", id: "FM" },
            { name: "Republic of Maldova", dial_code: "+373", id: "MD" },
            { name: "Mozambique", dial_code: "+258", id: "MZ" },
            { name: "Palestinian Territory, Occupied", dial_code: "+970", id: "PS" },
            { name: "Pitcairn", dial_code: "+872", id: "PN" },
            { name: "Réunion", dial_code: "+262", id: "RE" },
            { name: "Russia", dial_code: "+7", id: "RU" },
            { name: "Saint Barthélemy", dial_code: "+590", id: "BL" },
            { name: "Saint Helena, Ascension and Tristan Da Cunha", dial_code: "+290", id: "SH" },
            { name: "Saint Kitts and Nevis", dial_code: "+1869", id: "KN" },
            { name: "Saint Lucia", dial_code: "+1758", id: "LC" },
            { name: "Saint Martin", dial_code: "+590", id: "MF" },
            { name: "Saint Pierre and Miquelon", dial_code: "+508", id: "PM" },
            { name: "Saint Vincent and the Grenadines", dial_code: "+1784", id: "VC" },
            { name: "Sao Tome and Principe", dial_code: "+239", id: "ST" },
            { name: "Somalia", dial_code: "+252", id: "SO" },
            { name: "Svalbard and Jan Mayen", dial_code: "+47", id: "SJ" },
            { name: "Syrian Arab Republic", dial_code: "+963", id: "SY" },
            { name: "Taiwan, Province of China", dial_code: "+886", id: "TW" },
            { name: "Tanzania, United Republic of", dial_code: "+255", id: "TZ" },
            { name: "Timor-Leste", dial_code: "+670", id: "TL" },
            { name: "Venezuela, Bolivarian Republic of", dial_code: "+58", id: "VE" },
            { name: "Viet Nam", dial_code: "+84", id: "VN" },
            { name: "Virgin Islands, British", dial_code: "+1284", id: "VG" },
            { name: "Virgin Islands, U.S.", dial_code: "+1340", id: "VI" }
        ])

    } catch (err) {
        console.error(err)
    } finally {
        process.exit()
    }
})()
